Add more validation
usegalaxy-eu/tiaas2 pull request #11
Opened 2020-11-20 23:22 UTC by ic4f

Validate date precedence, start date, identifier format.
+ Some refactoring

Start date validation is done on the form because it's a user-facing requirement: a start date in the past is a valid value in the admin. Date precedence is a model requirement, so it's defined on the model.

There's more to be done, but this seems like a good batch.

2020-11-23 09:33 UTC, hexylena requested changes
the explicit validator is definitely an improvement!

2020-11-23 09:33 UTC, hexylena commented on training/templates/training/register.html
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
seems in reflowing this bit you dropped the closing </p>?

2020-11-23 09:33 UTC, hexylena commented on training/templates/training/register.html
> +<p>Please note that we do provide this service for free to everyone, so we ask you kindly likewise
and again here, dropped tag when you reflowed.

If you need to reflow could you do

```
<p>
  some text
  more text
</p>
```

I find that a bit easier to read and ensure we're not dropping closing tags

2020-11-23 09:33 UTC, hexylena commented on training/templates/training/register.html
> +<p>Please note that we do provide this service for free to everyone, so we ask you kindly likewise
ok, evidently a consistent problem with your editor.

2020-11-23 09:33 UTC, hexylena commented on training/validators.py
> +    regex=re.compile(r'^[-a-z0-9_]+\Z'),
I've never seen `\Z` used before, why not `$`?

2020-11-23 09:33 UTC, hexylena commented on training/views.py
> +    else:
1. any reason you inverted the condition?
2. If we're going to edit this, I'd prefer this style to error early and often.

```
if request.method != "POST"
	form = TrainingForm()
	return

if not form.is_valid():
	handle this

form.save()
if email:
  ....
```

2020-11-23 21:49 UTC, ic4f commented on training/views.py
> +    else:
> 1. any reason you inverted the condition?

Very minor. Slightly improved readability: there are 2 nested `if` statements inside the first clause; I think moving the `else`clause up makes it easier to read. I think the logic (first checking if it's *not* a post) reads the same, but this may be completely subjective, and if you think the previous version was better, I'll change it back.

> 2. If we're going to edit this, I'd prefer this style to error early and often.
> 
> ```
> if request.method != "POST"
> 	form = TrainingForm()
> 	return
> 
> if not form.is_valid():
> 	handle this
> 
> form.save()
> if email:
>   ....
> ```

We need to `return render(request, "training/register.html", {"form": form, "settings": settings})` if the form is blank OR if `not form.is_valid()` - so we'd have that line appearing twice if we were to return right after checking one of those cases. 

The code follows the same steps as the previous version - check http method, instantiate form if post, call `is_valid`, return if there are errors - so I think we are checking for form errors as early as possible, unless I'm missing it? If I'm mistaken, we are considering these 3 versions: (a) new, (b) previous, (c) in code review. I slightly prefer a; I'm perfectly fine with b, I'm not excited about c:

``` 
if method is not post:
    form = blank form
else:
    form = loaded from request
    if form is valid:
        process it
        return: happy.html
return: register.html
```	
```
if method is post:
    form = loaded from request
    if form is valid:
        process it
        return: happy.html
    else:
        form = blank form
return: register.html
```	
```
if method is not post:
    form = blank form
    return: register.html
form = loaded from request
if form is not valid:
    return: register.html
process it
return: happy.html
```

2020-11-23 21:56 UTC, ic4f commented on training/validators.py
> +    regex=re.compile(r'^[-a-z0-9_]+\Z'),
It was mindless copying!
https://github.com/django/django/blob/master/django/core/validators.py#L255
Yes, let's replace with `$` - it's more appropriate here (no multilines in training identifiers!)

2020-11-23 22:10 UTC, ic4f commented on training/templates/training/register.html
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
It was intentional, although I don't have a strong preference here - I'm 100% fine with doing whatever with `<p>` or any other html/css thing. 
The reason was this. The closing tag for the `p` element is optional here (same for `li` - and I dropped that too). So, less clutter. Besides, to me, having just one opening paragraph tag makes it easier to read and edit paragraph text in html, especially when there are multiple paragraphs: it's like plain text with the addition of a leading `<p>`. But again, this is very subjective, and I'll be happy with any other formatting style.

2020-11-23 22:12 UTC, ic4f commented on training/templates/training/register.html
> +<p>Please note that we do provide this service for free to everyone, so we ask you kindly likewise
Ah, I just posted a response to the previous comment (without reading this one). Yes, of course, I'll change it back.

2020-11-24 10:22 UTC, hexylena commented on training/templates/training/register.html
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
Wow, I had not realised that was optional. not something I'd seen before.

Ok, thanks for adding them back, I think I have a preference for that, I know it's clutter but it looks so much more valid-html to me. *That said* this is a ton of HTML content and html sucks to edit. We could replace this with a variable (more configurability for folks) + render that variable as markdown. Which would solve the issue of humans having to write html. How would you feel about that?

2020-11-24 10:25 UTC, hexylena commented on training/views.py
> +    else:
Sounds good, comment retracted, a or b is fine.

2020-11-24 16:30 UTC, ic4f commented on training/templates/training/register.html
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
I think using variable(s)/markdown is a very good idea (and totally agree on editing HTML content). Do you mind if we do that in a separate PR? (there may be more issues to consider about the form's content - so it's generic and customizable enough to suit the needs of, at least, both EU and main - and that might affect how we go about this, but I don't have a full picture of main's needs as of yet.)

The closing p tag is  [conditionally optional](https://html.spec.whatwg.org/#the-p-element) (see tag omission), but I've never been able to come up with a reasonable use case when none of those conditions apply. Either way looks fine to me.

2020-11-24 16:32 UTC, ic4f commented on training/views.py
> +    else:
Thank you! I'll keep version "a" then.

2020-11-24 16:35 UTC, hexylena commented
Sure that's all fine

tir. 24. nov. 2020, 17:31 skrev Sergey Golitsynskiy <
notifications@github.com>:

> *@ic4f* commented on this pull request.
> ------------------------------
>
> In training/templates/training/register.html
> <https://github.com/usegalaxy-eu/tiaas2/pull/11#discussion_r529712285>:
>
> > -<p>
> -We want to help you conduct your training seminars. Where you provide the training, we can provide you training infrastructure as a service (TIaaS). Some of the benefits of using our {{ settings.TIAAS_OWNER }} infrastructure:
> -</p>
> +<h1>{{ settings.TIAAS_OWNER }}'s Training Infrastructure as a Service</h1>
> +
> +{% if form.all_error_messages %}
> +    <div class="alert alert-danger">Please correct the following errors in the form below:
> +        <ul>
> +        {% for msg in form.all_error_messages %}
> +            <li>{{ msg }}
> +        {% endfor%}
> +        </ul>
> +    </div>
> +{% endif %}
> +
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
>
> I think using variable(s)/markdown is a very good idea (and totally agree
> on editing HTML content). Do you mind if we do that in a separate PR?
> (there may be more issues to consider about the form's content - so it's
> generic and customizable enough to suit the needs of, at least, both EU and
> main - and that might affect how we go about this, but I don't have a full
> picture of main's needs as of yet.)
>
> The closing p tag is conditionally optional
> <https://html.spec.whatwg.org/#the-p-element> (see tag omission), but
> I've never been able to come up with a reasonable use case when none of
> those conditions apply. Either way looks fine to me.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/usegalaxy-eu/tiaas2/pull/11#discussion_r529712285>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADP7O4CKJAMG2OBX43WIUDSRPNUHANCNFSM4T5LXPDQ>
> .
>

2020-11-24 16:38 UTC, hexylena commented on training/templates/training/register.html
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
Fine for a separate pr.

Yeah I found a similar link. Wild. If you don't mind I'd like to keep the closing tags for now, just for explicitness.

Otherwise looks good

2020-11-24 16:40 UTC, ic4f commented on training/templates/training/register.html
> +<p>We want to help you conduct your training seminars. Where you provide the training, we can
> Yeah I found a similar link. Wild. If you don't mind I'd like to keep the closing tags for now, just for explicitness.

Yes, of course!

2020-11-24 16:41 UTC, ic4f commented
Thank you for the review!

2020-11-24 16:42 UTC, merged